### ISSUE TITLE
滑动朋友列表到收取能量时，没有点进去用户

### ISSUE THREAD

**Issue by PikachuWu** [Nick-Hopps/Ant-Forest-autoscript#100]
日志显示错误
java.lang.IllegalArgumentException:Path bounds must not be negative

**Comment by Nick-Hopps** [comment]
手机分辨率的问题，你是什么手机？

**Comment by kaigedong** [comment]
我mate20 同样的问题。不点进去用户

**Comment by kaigedong** [comment]
> 我mate20 同样的问题。不点进去用户

解决了！加群看了视频，似乎我原来使用的方式有点小问题。
