### ISSUE TITLE
蚂蚁森林小程序更新后无法识别J_rank_list_append OR J_rank_list

### ISSUE THREAD

**Issue by AtypicalCoder** [Nick-Hopps/Ant-Forest-autoscript#105]
不知作者是如何找到好友列表的父组件ID的, 期待回复交流

**Comment by lunachy** [comment]
而且好友排行榜也没有了，
while(!friendListWaiting()) sleep(1000); 这行会产生死循环

**Comment by ksfallen** [comment]
直接拿好友列表， 进行循环
```js
      friends_list = className('android.view.View').depth(7).find()
      if (friends_list.length > 0) {
        friends_list.forEach(function (fri) {
          if (fri.visibleToUser() && fri.childCount() > 3)
            // ...
        });
        // ...
      }
```

**Comment by ksfallen** [comment]
> 而且好友排行榜也没有了，
> while(!friendListWaiting()) sleep(1000); 这行会产生死循环

用  `总排行榜` 代替 `好友排行榜`

**Comment by DeserveL** [comment]
> 直接拿好友列表， 进行循环
> 
> ```js
>       friends_list = className('android.view.View').depth(7).find()
>       if (friends_list.length > 0) {
>         friends_list.forEach(function (fri) {
>           if (fri.visibleToUser() && fri.childCount() > 3)
>             // ...
>         });
>         // ...
>       }
> ```

fri.childCount() 为1，求解

**Comment by 835732349** [comment]
> > 直接拿好友列表， 进行循环
> > ```js
> >       friends_list = className('android.view.View').depth(7).find()
> >       if (friends_list.length > 0) {
> >         friends_list.forEach(function (fri) {
> >           if (fri.visibleToUser() && fri.childCount() > 3)
> >             // ...
> >         });
> >         // ...
> >       }
> > ```
> 
> fri.childCount() 为1，求解

friends_list = className('android.view.View').depth(7).find()这句代码意思是找处于第七层的view，处于第七层的view都可能被寻找到，所以你找到的可能不是好友列表的view

**Comment by AtypicalCoder** [comment]
> 直接拿好友列表， 进行循环
> 
> ```js
>       friends_list = className('android.view.View').depth(7).find()
>       if (friends_list.length > 0) {
>         friends_list.forEach(function (fri) {
>           if (fri.visibleToUser() && fri.childCount() > 3)
>             // ...
>         });
>         // ...
>       }
> ```

蚂蚁森林全部改成viewgroup了,用控件没法识别的到呀
