### ISSUE TITLE
蚂蚁森林更新后，小手无法识别

### ISSUE THREAD

**Issue by zb861359** [Nick-Hopps/Ant-Forest-autoscript#106]
蚂蚁森林更新后，根据新的排行榜，已修改代码中的相关部分，列表可以正常上滑，但是出现小手无法识别的情况。请问应该怎么解决

**Comment by 54lH** [comment]
同问

**Comment by xinsibo** [comment]
同 催更了

**Comment by xinsibo** [comment]
日常催更

**Comment by TonyJiangWJ** [comment]
作者考研 没时间更新 可以先试试我的: [https://github.com/TonyJiangWJ/Ant-Forest](https://github.com/TonyJiangWJ/Ant-Forest)

**Comment by xinsibo** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "TonyJiangWJ"<notifications@github.com&gt;; 
发送时间: 2019年12月3日(星期二) 上午9:58
收件人: "Nick-Hopps/Ant-Forest-autoscript"<Ant-Forest-autoscript@noreply.github.com&gt;; 
抄送: "信思波"<419012037@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Nick-Hopps/Ant-Forest-autoscript] 蚂蚁森林更新后，小手无法识别 (#106)




作者考研 没时间更新 可以先试试我的: https://github.com/TonyJiangWJ/Ant-Forest-autoscript
