### ISSUE TITLE
运行之后可以自动进入蚂蚁森林，但是没有任何操作就退出来了，然后就是再进入蚂蚁森林，再退出...  循环

### ISSUE THREAD

**Issue by wfxcode** [Nick-Hopps/Ant-Forest-autoscript#109]
![Screenshot_2020-11-01-14-01-49-458_org autojs aut](https://user-images.githubusercontent.com/41145041/97796299-432bc900-1c4b-11eb-93bc-d366004e6f4b.jpg)

**Comment by Nick-Hopps** [comment]
因为项目已经很久没更新了，建议加群然后用群里另外两位还在持续开发的大佬的版本。
