### ISSUE TITLE
执行到 descEndsWith("背包").waitFor(); 的时候就卡住了，不再往下执行

### ISSUE THREAD

**Issue by renzhenfei** [Nick-Hopps/Ant-Forest-autoscript#14]

**Comment by Nick-Hopps** [comment]
有日志吗，发上来看一下

**Comment by renzhenfei** [comment]
> 有日志吗，发上来看一下

![_20190220_131528](https://user-images.githubusercontent.com/15669071/53068069-f99c5880-3511-11e9-9044-371bf89627e3.png)
最后一行是我自己打印的
![06 rx qdzuvpy2edtlb ezk](https://user-images.githubusercontent.com/15669071/53068090-12a50980-3512-11e9-909e-32552cb11a33.png)

**Comment by Nick-Hopps** [comment]
你的 autojs 版本是多少？

**Comment by Nick-Hopps** [comment]
你的 autojs 版本是多少？

**Comment by renzhenfei** [comment]
> 你的 autojs 版本是多少？
检查更新了下
![_20190220_143851](https://user-images.githubusercontent.com/15669071/53071470-4df90580-351d-11e9-9d5a-bdce0fa63b83.png)

**Comment by Nick-Hopps** [comment]
我的是 4.1.1

**Comment by mel0us** [comment]
新版的支付宝里面蚂蚁森林的控件布局变了，所以找不到 背包🎒

**Comment by Nick-Hopps** [comment]
> 
> 
> 新版的支付宝里面蚂蚁森林的控件布局变了，所以找不到 背包🎒

我刚刚看了一下并没有问题，背包还是可以找到

**Comment by mel0us** [comment]
我估计支付宝有加载页的缓存机制，你可以清空支付宝的本地数据，重新登录试试看吗？
如果还能找到“背包”的话，可能跟手机系统有关了。。

**Comment by Nick-Hopps** [comment]
> 
> 
> 我估计支付宝有加载页的缓存机制，你可以清空支付宝的本地数据，重新登录试试看吗？
> 如果还能找到“背包”的话，可能跟手机系统有关了。。

一样的，并没有问题

**Comment by Nick-Hopps** [comment]
> 
> 
> 我估计支付宝有加载页的缓存机制，你可以清空支付宝的本地数据，重新登录试试看吗？
> 如果还能找到“背包”的话，可能跟手机系统有关了。。

有时候找不到控件是软件的问题，重新打开几次蚂蚁森林就能找到了

**Comment by mel0us** [comment]
用"应用变量"模拟了不同手机型号，发现三星手机可以找到"背包"控件，而vivo不能。说明蚂蚁森林可能对不同机型有不同的布局优化。

**Comment by renzhenfei** [comment]
> 用"应用变量"模拟了不同手机型号，发现三星手机可以找到"背包"控件，而vivo不能。说明蚂蚁森林可能对不同机型有不同的布局优化。

我就是vivo测试的，我说怎么老是不行

**Comment by Nick-Hopps** [comment]
所以这个问题是由于支付宝对不同手机的优化不同导致的？

**Comment by oldfish96** [comment]
> 所以这个问题是由于支付宝对不同手机的优化不同导致的？

我的vivo也是,凡是带背包的都过不了

**Comment by Nick-Hopps** [comment]
> 
> 
> > 所以这个问题是由于支付宝对不同手机的优化不同导致的？
> 
> 我的vivo也是,凡是带背包的都过不了

那个函数的作用就是阻塞运行直到当前页面能找到一个 desc 为 “背包” 的控件为止，如果运行卡住，你可以看看你的蚂蚁森林的背包按钮的控件的 desc 的值

**Comment by oldfish96** [comment]
> > > 所以这个问题是由于支付宝对不同手机的优化不同导致的？
> > 
> > 
> > 我的vivo也是,凡是带背包的都过不了
> 
> 那个函数的作用就是阻塞运行直到当前页面能找到一个 desc 为 “背包” 的控件为止，如果运行卡住，你可以看看你的蚂蚁森林的背包按钮的控件的 desc 的值

背包好像没有控件化还有就是能量球也是一样,找了很久都没有找到

**Comment by zhfang1125** [comment]
我昨天也出现该问题，之前用了一个多月都是OK的

**Comment by zhfang1125** [comment]
两部手机 红米 和中兴 都同时不行了

**Comment by gitbruce** [comment]
有时候‘背包’出现在desc，有时候出现在text里。
如果出现在text里，就没法用了
