### ISSUE TITLE
希望能支持多语言

### ISSUE THREAD

**Issue by chuanzz** [Nick-Hopps/Ant-Forest-autoscript#15]
个人所有app都是用英语的，相信也有用繁体中文之类的同学，希望能加一个多语言的设置。
将几个字符串拿出来用变量替代应该不是很大工程，虽然能帮助的人不多，但还是有人能受益的。
希望采纳

**Comment by Nick-Hopps** [comment]
这个还真没考虑到，我有空加上吧

**Comment by YinHang119** [comment]
恩，目前的脚本，手机语言为中文正常运行；手机语言调至英语后，进入蚂蚁森林个人首页，显示“还有XX分钟收取”，然后就停留在该界面
