### ISSUE TITLE
not found cardview?

### ISSUE THREAD

**Issue by KingteeLoki-Ran** [Nick-Hopps/Ant-Forest-autoscript#16]
![screenshot_20190222-002913](https://user-images.githubusercontent.com/23162326/53185136-5fcfcb00-3639-11e9-81a0-c9ba9c62fd65.jpg)

**Comment by KingteeLoki-Ran** [comment]
honour9 unlock failed

**Comment by Nick-Hopps** [comment]
这个是 autojs 版本的问题，建议去下载 4.1.0 以上版本

**Comment by KingteeLoki-Ran** [comment]
![screenshot_20190222-011345](https://user-images.githubusercontent.com/23162326/53187951-3619a280-363f-11e9-9a4e-ef2cacabc355.jpg)
直接运行jiao脚本正常，当设置定时任务后会卡在这里

**Comment by ForgetSky** [comment]
autojs 4.1.0版本在哪可以下载？

**Comment by Nick-Hopps** [comment]
> 
> 
> autojs 4.1.0版本在哪可以下载？

方法1：加入 autojs 内测群
方法2：https://tieba.baidu.com/p/6024491783，往下翻，我有上传 4.1.1 版本
