### ISSUE TITLE
稳定全天运行的建议

### ISSUE THREAD

**Issue by springga** [Nick-Hopps/Ant-Forest-autoscript#17]
autojs中的延时执行有两个问题：
1. 时间不准确，无法准时执行
2. 会被音量上键全局终止，停止执行

经测试使用tasker管理定时任务，调用autojs执行的方案更稳定，基本保证全天准时执行，关键在于autojs向tasker传递下次执行时间的参数，可参考[Tasker 与 Autojs 之间如何传递数据](https://www.jianshu.com/p/ec102bd99213)的后半部分

**Comment by Nick-Hopps** [comment]
问题1是软件本身的问题，问题2是软件设置的问题，使用tasker的确可以，但是我本身的需求只是早上半个小时左右的时间收取，因此并没有设计成使用 Tasker 的方式。

**Comment by lunachy** [comment]
> 问题1是软件本身的问题，问题2是软件设置的问题，使用tasker的确可以，但是我本身的需求只是早上半个小时左右的时间收取，因此并没有设计成使用 Tasker 的方式。

定时不准确，如果不用tasker，你是早上醒来手动执行么？睡懒觉很重要啊……
