### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Chrisleung** [Nick-Hopps/Ant-Forest-autoscript#2]
当好友的能量在倒计时时会报这个错误

错误: Wrapped java.lang.lllegalArgumentException: x must be < bitmap.width() (___images___.js#123)

**Comment by Nick-Hopps** [comment]
能提供截图吗？我没有遇到过这个问题

**Comment by Chrisleung** [comment]
Android: 7.0
Auto.js: 3.1.0 Beta

![1838412122](https://user-images.githubusercontent.com/4082136/51978352-f2f76400-24c4-11e9-806a-ba0f35827708.jpg)

**Comment by Chrisleung** [comment]
多点查色改为按图片查找就正常了
因为Auto.js是beta版的原因？

**Comment by Nick-Hopps** [comment]
autojs 已经 4.1.0 了，换个新版本试试

**Comment by Chrisleung** [comment]
换4.0.5Alpha后正常了
