### ISSUE TITLE
module is not defined

### ISSUE THREAD

**Issue by Fitka16** [Nick-Hopps/Ant-Forest-autoscript#25]
三星S9+ 运行程序后 显示 module is not defined

**Comment by Nick-Hopps** [comment]
运行的什么程序？具体的日志是什么？提问要具体。

**Comment by Fitka16** [comment]
运行Ant_forest
日志:[/storage/emulated/0/脚本/Ant-Forest-autoscript-master/core/Ant_forest.js]运行结束，用时0.011000秒 
10:40:49.954/V: 开始运行[/storage/emulated/0/脚本/Ant-Forest-autoscript-master/core/Ant_forest.js]
10:40:49.965/E: ReferenceError: "module" is not defined. (<Ant_forest>#353)
	at script(<Ant_forest>:353)
不会发截图。。。

**Comment by Nick-Hopps** [comment]
运行 main.js，看首页教程

**Comment by Fitka16** [comment]
谢谢
