### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Benjeming** [Nick-Hopps/Ant-Forest-autoscript#26]
运行的时候出现一个Bug，错误代码如下
**

> Wrapped java.lang.IllegalStateException ： nodelnfo. viewldResourceName must not be null

**
在开始收取好友能量的时候也出现了Bug。
刚去百度了下，这个Bug是因为 Auto.js 版本的问题. Auto.js版本 请下载  4.0.1 Bate。 新版本4.0.5Alpha会报错

**Comment by Nick-Hopps** [comment]
请下载 Autojs 4.1.1，贴吧里面我有上传
