### ISSUE TITLE
收取自己的能量会被活动干扰

### ISSUE THREAD

**Issue by duyi324** [Nick-Hopps/Ant-Forest-autoscript#27]
当蚂蚁森林页面，自己的能量球周围出现活动时会点击进入活动页面，导致无法运行到收取好友能量。
比如，今天是3月13日，蚂蚁森林有个`春种`活动，脚本会打开春种活动页面然后就一直在这里等待了。

![image](https://user-images.githubusercontent.com/8315837/54257236-a611ad80-4599-11e9-8648-bf5cce84049e.png)

**Comment by Nick-Hopps** [comment]
是下载的最新版本脚本吗？

**Comment by weilixing00** [comment]
最近的版本也是这样  一样点到种树的界面。尝试修改颜色值 也没多大用

**Comment by Nick-Hopps** [comment]
> 
> 
> 最近的版本也是这样 一样点到种树的界面。尝试修改颜色值 也没多大用

这已经不是脚本的问题了，脚本已经在几台手机测试过没有问题了

**Comment by Nick-Hopps** [comment]
请更新 2.1.0 版本
