### ISSUE TITLE
 魅族15plus无法运行

### ISSUE THREAD

**Issue by chaisheng19** [Nick-Hopps/Ant-Forest-autoscript#28]
12:00:31.189/E: ReferenceError: "activity" is not defined. (file:///android_asset/modules/__ui__.js#14)
ReferenceError: "activity" is not defined.
    at file:///android_asset/modules/__ui__.js:14:0
    at draw_view (/storage/emulated/0/脚本/Ant-Forest-autoscript-master/config.js:32:0)
    at /storage/emulated/0/脚本/Ant-Forest-autoscript-master/config.js:181:0

**Comment by Nick-Hopps** [comment]
注意看贴吧。。。这个问题问了很多次了，要换最新版的 autojs， 4.1.1的
