### ISSUE TITLE
定时任务解锁屏幕时报错

### ISSUE THREAD

**Issue by Chrisleung** [Nick-Hopps/Ant-Forest-autoscript#3]
系统: MIUI 9    Android 7.0
Auto.js: 4.0.5 Alpha

> 07:00:01.645/E: Wrapped java.lang.IllegalStateException: nodeInfo.viewIdResourceName must not be null (file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/lib/Unlock.js#138)
Wrapped java.lang.IllegalStateException: nodeInfo.viewIdResourceName must not be null
    at file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/lib/Unlock.js:138:0
    at file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/lib/Unlock.js:121:0
    at file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/lib/Ant_forest.js:222:0
    at /storage/emulated/0/脚本/Ant-Forest-autoscript-master/main.js:35:0

**Comment by Nick-Hopps** [comment]
小米的解锁和其他手机好像有点不一样，身边没有小米手机所以没法做适配，我待会找一下别人的代码看看吧。

**Comment by Nick-Hopps** [comment]
https://github.com/e1399579/autojs 你看看他这个，应该可以吧，我没有小米没法测试，他的 Secure.js 里面，可以找到 MIUI 和 MIUI10

**Comment by Chrisleung** [comment]
测试了，会报错
等年后连电脑再测试一下

> 21:16:12.948/E: Wrapped java.lang.IllegalStateException: nodeInfo.viewIdResourceName must not be null (file:/storage/emulated/0/脚本/autojs-master/Secure.js#205)
Wrapped java.lang.IllegalStateException: nodeInfo.viewIdResourceName must not be null
    at file:/storage/emulated/0/脚本/autojs-master/Secure.js:205:0
    at file:/storage/emulated/0/脚本/autojs-master/Secure.js:45:0
    at /storage/emulated/0/脚本/autojs-master/解锁.js:24:0

**Comment by Nick-Hopps** [comment]
错误是因为控件 ID 没找到，你可以用 uiautomatorviewer 查看一下解锁界面控件 ID
