### ISSUE TITLE
手机解锁画面不上滑，无法弹出密码页面

### ISSUE THREAD

**Issue by ycy976824423** [Nick-Hopps/Ant-Forest-autoscript#31]
由于锁屏会根据手指的滑动速度决定是否弹出密码页面。建议用以下的方式上滑。

>       var xyArr = [220]
>       var x0=device.width/2
>       var y0=device.height/4*3
>       var angle = 0
>       var x = 0
>       var y = 0
>       for (let i = 0; i < 30; i++) {
>         y = x * tan(angle)
>         log(y)
>         if((y0-y)<0){
>           break
>         }
>         var xy = [x0+x,y0-y]
>         xyArr.push(xy)
>         x += 5;
>         angle += 3
>       }
>       gesture.apply(null,xyArr)
>       function tan(angle) {
>         return Math.tan(angle * Math.PI / 180);
>       }

**Comment by Nick-Hopps** [comment]
因人而异，手机的问题没法统一，mark一下，有需要的自己改就好了
