### ISSUE TITLE
定时任务定在第二天早上，程序没有正常执行。

### ISSUE THREAD

**Issue by fakerLinXiao** [Nick-Hopps/Ant-Forest-autoscript#32]
![QQ20190321-0](https://user-images.githubusercontent.com/25616054/54731872-ab8b7b00-4bcb-11e9-8848-f9c2495087c8.png)

白天的定时任务都正常执行，可是红框中定的第二天早上7：17的任务只显示执行中，不在执行了。

期望可以正常执行

**Comment by Nick-Hopps** [comment]
autojs 后台自启打开

**Comment by ghost** [comment]
> autojs 后台自启打开

话说有定时任务这功能吗？我怎么没看到……之前晚上偷完能量，只能自己搞个毫秒计算的方法，再把延时运行脚本加上去……
