### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by lippor** [Nick-Hopps/Ant-Forest-autoscript#33]
1、运行一两遍会导致auto.js崩溃，并且日志也被清空了。
2、有没有什么方法，开始不用获取截屏授权，直接运行。
3、经常运行一遍结束后，卡在好友列表最低端不运行。

1，3两个问题比较急切。手机是小米8

**Comment by Nick-Hopps** [comment]
软件问题，非脚本问题
