### ISSUE TITLE
运行config出错

### ISSUE THREAD

**Issue by aexhjc** [Nick-Hopps/Ant-Forest-autoscript#35]
手机：HTC U11
系统：HTC港版8.0
最新版脚本，4.0.1beta版本的auto.js
config.js运行报错如下：

22:05:32.702/E: ReferenceError: "activity" is not defined. (__ui__.js#15)
	at script(__ui__.js:15)
	at script.draw_view(<config>:32)
	at script(<config>:181)

**Comment by haovxuan** [comment]
一样的情况，main我也运行不了

**Comment by Nick-Hopps** [comment]
仔细看说明
