### ISSUE TITLE
华为荣耀magic2问题汇总

### ISSUE THREAD

**Issue by ghost** [Nick-Hopps/Ant-Forest-autoscript#41]
/E: Wrapped android.view.InflateException: android.view.InflateException: java.lang.ClassNotFoundException: android.widget.card (__floaty__.js#9)
	at script(__floaty__.js:9)
	at script(file:/storage/emulated/0/脚本/Ant-Forest-autoscript/core/Ant_forest.js:52)
	at script(file:/storage/emulated/0/脚本/Ant-Forest-autoscript/core/Ant_forest.js:202)
	at script(file:/storage/emulated/0/脚本/Ant-Forest-autoscript/core/Ant_forest.js:362)
	at script(file:/storage/emulated/0/脚本/Ant-Forest-autoscript/core/Ant_forest.js:376)
	at script(<main>:51)

华为荣耀magic2报错~ 收集完一圈后（从“没有更多了”回到好友排行榜时）报错

**Comment by Smeda1024** [comment]
看了一下unlock.js里面的驱动用的是HUAWEI_EMUI8，而我的手机是荣耀magic2的驱动。呃~我并不晓得官网的驱动命名，所以就尝试把unlock相关功能代码注释掉了。还是会报这个错，麻烦大神帮忙解决一下，谢谢。对了，我这边的config.js配置文件在auto.js上也是运行不了的，代码和app都是最新的。

**Comment by Smeda1024** [comment]
另外测出一个小问题，偷能量的时候不会帮助好友收取能量（绿色手的时候）。只有在好友排行榜里判断出可以帮好友收取的时候才会收取（也就是黄色手的时候）。

**Comment by ghost** [comment]
额，重新看了一下作者你的readme，恍悟到设备解锁代码那一块还是得自己写…最后，还是再次谢谢作者开源，学习了。

**Comment by Nick-Hopps** [comment]
毕竟不同手机控件不一定相同

**Comment by Smeda1024** [comment]
运行config.js无法显示ui界面，华为荣耀magic2和魅蓝1E都弹出报错：“activity is not defined”。另外，建议增加屏幕device.wakeUp();隔时激活屏幕功能，防止在偷能量的时候自动锁屏了。

**Comment by Smeda1024** [comment]
@Nick-Hopps 还有就是，统计偷能量的输出，建议偷一次就会输出本次偷取的数量，而不是完全偷完了才会报总共偷了多少能量…（因为我还没遇到过会输出总量的日志）

**Comment by Smeda1024** [comment]
额，我搞错了，偷能量的时候是有唤醒功能。但是偷完之后在桌面等待的时候就没有，因为我这里还没用过解锁功能，所以才提了一下在桌面等待时可加个定时唤醒功能。对了，这里我发现之前提的那个问题了，
```
Wrapped android.view.InflateException: android.view.InflateException: java.lang.ClassNotFoundException: android.widget.card (floaty.js#9)。
```
这个问题早上跑脚本貌似不会出现，但是晚上的时候基本会出现。初步断定是没有能量偷所致的，一旦报这个错跑完一圈能量后是返回到蚂蚁森林界面当中，而不像正常情况那样返回到桌面界面。

**Comment by Smeda1024** [comment]
emmm...看了一下auto.js的api才发现config.js要怎么运行，项目因为加了注释，"ui"; 不在第一行导致了配置脚本运行失败！

再者，nick你的更新检测应该是比对文件大小来判断是否要更新的吧。建议还是加个版本号的变量吧

**Comment by ghost** [comment]
@Nick-Hopps 
实测作者你的Unlock.js的划开图层的坐标有误差（不会划开图层，导致识别解锁方式失败），修改成以下的就没问题了。（参考了作者你分享的github作者e1399579的解锁.js修改的）
```
let x = _WIDTH / 2;
let y = _HEIGHT - 300;
this.automator.swipe(x, y, x, _HEIGHT / 2, 500);
```
