### ISSUE TITLE
autojs版本现在发布出来的最新的是4.0.5Alpha

### ISSUE THREAD

**Issue by askme-gpt** [Nick-Hopps/Ant-Forest-autoscript#42]
作者你好,谢谢开发了这个插件.你说基于autojs4.1.1,但是官方的最新版本是4.05,咋回事啊?

![image](https://user-images.githubusercontent.com/22534808/55713597-931cbc80-5a23-11e9-8c74-974aabee3ba7.png)

**Comment by Nick-Hopps** [comment]
说明这里不是最新的。。。最新的在内测群里面

**Comment by askme-gpt** [comment]
那我如果下载4.05的话,可以用你的代码吗?

**Comment by Nick-Hopps** [comment]
不行，非最新版本运行会出错
