### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by Avwqs** [Nick-Hopps/Ant-Forest-autoscript#43]
如果运行脚本之前支付宝在后台，并且已经进入好友排行的话，那么脚本将不能运行成功
运行日志：
23:56:46.506/D: 当前能量：159736
23:56:46.533/D: 无可收取能量
23:56:46.533/D: 开始收集好友能量
23:56:46.910/V: 
------------
[/storage/emulated/0/脚本/蚂蚁/main.js]运行结束，用时3.319000秒

**Comment by Nick-Hopps** [comment]
这不是BUG，本来就是这样的，脚本又不会为你判断你目前在哪个界面

**Comment by chinkeikin** [comment]
> ## 如果运行脚本之前支付宝在后台，并且已经进入好友排行的话，那么脚本将不能运行成功
> 运行日志：
> 23:56:46.506/D: 当前能量：159736
> 23:56:46.533/D: 无可收取能量
> 23:56:46.533/D: 开始收集好友能量
> 23:56:46.910/V:
> [/storage/emulated/0/脚本/蚂蚁/main.js]运行结束，用时3.319000秒

其实你可以自己修改一下，在脚本最开始运行的前面加上强制结束支付宝进程的命令然后延时一秒
