### ISSUE TITLE
不会有安全问题吧

### ISSUE THREAD

**Issue by StephenWu5** [Nick-Hopps/Ant-Forest-autoscript#45]
不会有安全问题吧,这个会不会搜集我的支付宝信息....

**Comment by StephenWu5** [comment]
运行是没啥问题

**Comment by ihx-rainbow** [comment]
目测感觉不会吧。。
不放心的话把main.js里32行检查更新注释下应该就不会自动连服务器了
` //engines.execScriptFile("./update.js");`

**Comment by Nick-Hopps** [comment]
觉得有问题自己读一下代码不就好了

**Comment by StephenWu5** [comment]
好
