### ISSUE TITLE
bug反馈，多个支付宝包名时，无法智能打开，只能手动选择

### ISSUE THREAD

**Issue by Chen-shijie** [Nick-Hopps/Ant-Forest-autoscript#46]
![15161952](https://user-images.githubusercontent.com/48749488/56021933-38de6d00-5d3d-11e9-85c1-a6d667e25216.jpg)

如图，魅族手机可以设置支付宝的应用分身，分身与原软件属于同一个包名，会导致打开支付宝的时候卡主，手动选择后才会继续运行

  // 进入蚂蚁森林主页
  const _start_app = function() {
    app.startActivity({        
      action: "VIEW",
      data: "alipays://platformapi/startapp?appId=60000002",    
    });
  }

请问下，这块能否进行优化

**Comment by Chen-shijie** [comment]
![image](https://user-images.githubusercontent.com/48749488/56022191-bd30f000-5d3d-11e9-9c59-fe5244696dc2.png)

**Comment by Nick-Hopps** [comment]
这是个别问题，没法统一
