### ISSUE TITLE
建议增加每次收取完毕的日志

### ISSUE THREAD

**Issue by chinkeikin** [Nick-Hopps/Ant-Forest-autoscript#48]
建议增加每次收取完毕的日志，在日志中打印一下本次收取了多少g能量
目前只有没能量收，运行结束的时候才会有悬浮窗提示，如果能每次打印一个log就更好了

**Comment by ghost** [comment]
这个简单，自己改一下代码就ok了。

**Comment by Nick-Hopps** [comment]
下次大更新会加上，现在主要的问题是好友数量太多的情况下识别会很慢

**Comment by ghost** [comment]
> 下次大更新会加上，现在主要的问题是好友数量太多的情况下识别会很慢

其实还有个问题，在没有好友的时候或者是很少的时候，代码会报错的
