### ISSUE TITLE
一加6运行config.js时报错，说页面没找到，如下图

### ISSUE THREAD

**Issue by githubnimabi** [Nick-Hopps/Ant-Forest-autoscript#49]
脚本文件已经更新到最新版本，手机是一加6 H2OS Android8.1，Autojs是酷安上最新的，版本是4.0.1beta，，，希望作者有时间能帮忙排查一下，万分感谢！
![Screenshot_20190415-144106](https://user-images.githubusercontent.com/12745231/56112267-1773c000-5f8d-11e9-8475-e7a0b5bd69b8.jpg)

**Comment by ghost** [comment]
刚开始我也以为是代码有问题，其实是auto.js版本的问题。
看了作者的简介你就会发现了……“基于 Autojs 的蚂蚁森林自动收能量脚本，采用 4.1.1 Alpha 版本开发。”
如果找不到这个版本，你可以把config.js的文档注释去掉，保证 “ui”; 在第一行

**Comment by githubnimabi** [comment]
好的，多谢多谢，我试试

**Comment by githubnimabi** [comment]
666，果然可以，多谢多谢

**Comment by ghost** [comment]
> 666，果然可以，多谢多谢

不客气。毕竟我也遇到这个问题了，能解决的就帮忙了，也不是大事。注意看一下报的什么异常，再结合auto.js的api看一下就ok了

**Comment by githubnimabi** [comment]
好的，刚装上这软件，，我学习学习，哈哈

**Comment by ghost** [comment]
> 666，果然可以，多谢多谢
建议你还是打开软件设置，找关于作者，加进QQ群下个新版本吧。不然后面你还会遇到问题的。一个floaty的问题，大概是在偷取能量结束的时候输出一共偷了多少的那句代码

**Comment by githubnimabi** [comment]
好的，多谢多谢
