### ISSUE TITLE
一些BUG

### ISSUE THREAD

**Issue by wyfang** [Nick-Hopps/Ant-Forest-autoscript#54]
设备：小米9

我认真观看运行，发现打开帮收朋友能量后，有时候点击进入，并不会帮忙收取，只是进入后就返回列表，速度非常快。有时候进入有能量可以偷取的朋友，也只是偷取了能量，并有没把帮忙收取的点击。

以及在早晨7点这种朋友能量多的时刻，计时似乎有点问题，具体表现在偷取能量列表上，有还剩1分钟的能量，结果当一次偷取完后，返回桌面，此时日志中显示下次偷取是4分钟。这导致错过很多能量偷取。

**Comment by wyfang** [comment]
还是代码就是这样写的？我不是很清楚。如果可以更完善代码，例如有存在一个用户设定值，例如 1分钟 ，则如果列表内存在1分钟的话，就可以执行设定的30次循环列表。因为有时候支付宝存在bug，1分钟一直存在，所以达到30次后，则返回支付宝首页再次进入等等。

以上只是不懂代码的提议，如有错误请见谅。

**Comment by wyfang** [comment]
希望增加 toast提醒 ，当用户在使用手机时，如果即将进行能量偷取，希望在偷取前有toast提醒，比如5秒倒计时。

**Comment by Nick-Hopps** [comment]
颜色偏移调高点就行了，还有这个脚本是给非手机使用时间用的，毕竟不是后台的脚本。

**Comment by wyfang** [comment]
好吧。还有就是有时候经常列表卡住不动，望修复。
有时候卡住的时候底部是显示“再试一次”，我手动点击后列表刷出来又自动下滑了。有时候不是，就是卡住不动了。还有时候我手动解锁屏幕，发现屏幕正处于我的森林，然后很快就进入好友列表，我感觉是不是亮屏不成功，直到我自己解锁了手机才进行偷取。

**Comment by wyfang** [comment]
今天早晨早起，认真观察了运行。运行平台：小米9。

现在的运行方式：我建立两个文件夹，一个设置循环35次，用于7点到7点30分的能量偷取；一个文件夹设置自动那种，用于7点30后的偷取。

设置35，是我早晨计算得来的，好友大约170人，需要35次来足以保证能运行到7:30，之所以不用默认的模式是因为我也测试了，如果使用默认的那个模式，7点自动运行，然后偷取一次后，手机日志通常里都显示下一次偷取为1分钟，然后就没有了，手机会自动被关屏。

所以即使不是早晨7点那段时间，使用默认模式，偷取一次后，如果有存在1分钟的，很大概率会程序就会卡住。感觉是手机的倒计时熄屏和程序的1分钟倒计时冲突，正好熄屏了，或者感觉像1分钟内的熄屏程序误判手机还处于活跃状态，所以不执行解锁了。

所以我认为，默认模式，最好有个设置，比如设置2分钟，如果有2分钟的能量，不如和循环那样，返回首页，再次进入。然后多余5分钟的，比如下次是10分钟，希望程序结束后，能自动有给锁屏，这样不仅省电，也可能减少错误。

**Comment by Nick-Hopps** [comment]
然而现有的权限下是没法锁屏的。。。

**Comment by mac-username** [comment]
运行config.js提示:referenceerror:"activity" is not defined.应该怎么解决呢

**Comment by mac-username** [comment]
第15行报错

**Comment by mac-username** [comment]
运行config.js提示:referenceerror:"activity" is not defined.第15行报错，应该怎么解决呢

**Comment by wyfang** [comment]
参考nova启动器的关屏，只要开启nova的无障碍服务就可以关屏，我相信autojs也可以。

**Comment by Nick-Hopps** [comment]
等作者更新咯=.=

**Comment by shinian97** [comment]
小米9  怎么自动解锁啊   求教一下

**Comment by wyfang** [comment]
不行的。最新开发版不能自动解锁了。
