### ISSUE TITLE
三星S9+ ReferenceError

### ISSUE THREAD

**Issue by zhaopinlei** [Nick-Hopps/Ant-Forest-autoscript#55]
![Screenshot_20190418-234203_Autojs](https://user-images.githubusercontent.com/36496984/56373750-3b0c6400-6234-11e9-9a33-06f1c5b8a9e1.jpg)
手机三星s9+，系统Android 9，autojs及此程序均为目前最新版本，运行config时出错，无法配置

**Comment by Nick-Hopps** [comment]
最新版 Autojs 没有这个问题，你仔细看看 README
