### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by buaashn** [Nick-Hopps/Ant-Forest-autoscript#59]
进入好友列表后crash并报出如下错误
18:31:26.357/E: Wrapped java.lang.IllegalStateException: nodeInfo.viewIdResourceName must not be null (file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/core/Ant_forest.js#346)
Wrapped java.lang.IllegalStateException: nodeInfo.viewIdResourceName must not be null
    at file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/core/Ant_forest.js:346:0
    at file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/core/Ant_forest.js:392:0
    at file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/core/Ant_forest.js:410:0
    at /storage/emulated/0/脚本/Ant-Forest-autoscript-master/main.js:53:0

**Comment by buaashn** [comment]
发现前面也有错误
应该与idEndsWith操作相关吧？
18:31:25.209/E: Thread[ScriptThread-56[/storage/emulated/0/脚本/Ant-Forest-autoscript-master/main.js] (Spawn-2),5]: Wrapped java.lang.IllegalStateException: nodeInfo.viewIdResourceName must not be null (file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/core/Ant_forest.js#40)
Wrapped java.lang.IllegalStateException: nodeInfo.viewIdResourceName must not be null
    at file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/core/Ant_forest.js:40:0

**Comment by Nick-Hopps** [comment]
是最新版 autojs？4.1.1 alpha 2？
