### ISSUE TITLE
帮好友收取能量异常

### ISSUE THREAD

**Issue by wzgrx** [Nick-Hopps/Ant-Forest-autoscript#6]
在好友界面不收取能量，直接结束，返回桌面

**Comment by Nick-Hopps** [comment]
autojs版本+错误信息

**Comment by nickzouli** [comment]
4.1.0 alpha5，能正常收自己和好友能量，帮好友收能量：进入好友界面后无操作2秒左右退出好友界面，每个好友界面都是这样。

**Comment by Nick-Hopps** [comment]
你看一下是不是用的最新版本的脚本

**Comment by wzgrx** [comment]
我的也会这样，只会收取自己的能量，好友的卡一下返回，用的是新脚本

**Comment by Nick-Hopps** [comment]
你试试调整一下 color_offset，调高点

**Comment by OneLeung** [comment]
春节好，最新版autojs app，安卓6.0，已root授权，
跳进蚂蚁森林页面进行收取时候会显示：本脚本需要此安卓版本7.0以上才能运行（_automator_.js#17）
thanks！

**Comment by Nick-Hopps** [comment]
> 
> 
> 春节好，最新版autojs app，安卓6.0，已root授权，
> 跳进蚂蚁森林页面进行收取时候会显示：本脚本需要此安卓版本7.0以上才能运行（_automator_.js#17）
> thanks！

首先确定你用的是最新的脚本，然后确定 Autojs 是否赋予 ROOT 权限

**Comment by OneLeung** [comment]
最新脚本+已赋予权限，可能这里个例。只是反馈下，总之感谢分享~

**Comment by Nick-Hopps** [comment]
有详细的 log 吗？发来我看一下
