### ISSUE TITLE
修改unlock后每次提醒更新

### ISSUE THREAD

**Issue by ti4311** [Nick-Hopps/Ant-Forest-autoscript#60]
如何关闭unlock的更新

**Comment by Nick-Hopps** [comment]
unlock.js 里面，有个忽略更新列表你仔细看看，把 unlock.js 添加进去就可以了

**Comment by vincenthsing** [comment]
main里面直接注释掉了~~32行

**Comment by ti4311** [comment]
> unlock.js 里面，有个忽略更新列表你仔细看看，把 unlock.js 添加进去就可以了

感谢感谢，我也直接吧更新注释掉了。

**Comment by ti4311** [comment]
> main里面直接注释掉了~~32行

我也是
