### ISSUE TITLE
为什么个文件夹脚本配置信息会被同步？

### ISSUE THREAD

**Issue by wyfang** [Nick-Hopps/Ant-Forest-autoscript#61]
我需要一个配置循环1次的偷取能量用于日出偷取。
我又复制了一份文件夹，取名不一样，配置循环25用于早晨7点偷取。为什么没办法呢？一个设置1后，另一个文件夹的配置也变成1。

顺便说下miui10最新开发版解锁全部沦陷了。

**Comment by Jianhua-Cui** [comment]
换解锁主题就可以正常解锁

**Comment by Nick-Hopps** [comment]
配置是软件本地保存的，也就是说一个 Autojs 只有一份配置，其他文件会共享配置

**Comment by cyiande** [comment]
你可以修改config.js里保存配置的key
var config = storages.create("ant_forest_config");
然后就不会被覆盖了

**Comment by wyfang** [comment]
@cyiande 我修改
var config = storages.create("ant_forest_config");
为：
var config = storages.create("ant_forest_config1");
后，进入森林后就没有操作了。似乎不起作用了。

**Comment by Nick-Hopps** [comment]
> 
> 
> @cyiande 我修改
> var config = storages.create("ant_forest_config");
> 为：
> var config = storages.create("ant_forest_config1");
> 后，进入森林后就没有操作了。似乎不起作用了。

设置里面的配置和主程序里面的配置都要改的
