### ISSUE TITLE
脚本运行时有时候会停在自己森林主页，不继续好友能量

### ISSUE THREAD

**Issue by xapwv** [Nick-Hopps/Ant-Forest-autoscript#63]

**Comment by Jianhua-Cui** [comment]
我也遇到过这种情况，需要手动展开更多好友才能继续运行。只有在计时模式才会出现。

**Comment by Jianhua-Cui** [comment]
检查了代码内的问题，发现是scrollDown函数在刚打开排行榜的时候无法触发加载更多。我的解决办法是将scrollDown函数替换为gesture(500,[540,1800],[540,500]); 代码在Ant_Forest的_find_and_collect函数内。同时最好屏蔽自动更新，因为会覆盖掉修改过的代码。希望作者大大能看到这个问题呀

**Comment by xapwv** [comment]
一开始就把更新的代码注掉了，哈哈

**Comment by Nick-Hopps** [comment]
做完毕业设计之后会针对这些问题进行更新

**Comment by November-raining** [comment]
gesture(500,[540,1800],[540,500]) 做完替换后基本正常
不过调整了第一参数，时间500ms会一定几率漏过最后几个可收取好友，直接退出
时间调整到300ms甚至更低，又有一定概率在打开蚂蚁森林好友列表时漏过前几个可收取的好友，直接下滑了
