### ISSUE TITLE
能量收取完毕后，停留在“没有更多了”界面，没有退出支付宝

### ISSUE THREAD

**Issue by YinHang119** [Nick-Hopps/Ant-Forest-autoscript#64]
【手机】三星S8
【系统】Android 9
【软件版本】4.1.1 Alpha2
【脚本】最新

现象：
1.能量收取正常，收取完毕后，页面停留在最下方“没有更多了”界面，没有退出蚂蚁森林、没有退出支付宝
2.手动退出支付宝，手机默认向右侧滑动，停留主界面的最右侧一个页面（需要手动进auto.js将正在运行中的脚本关闭，才可以停止手机上的操作）

![1](https://user-images.githubusercontent.com/39940790/57507195-a7a8e900-7330-11e9-80b5-e27e2a420b55.jpg)

**Comment by DeserveL** [comment]
我也遇到了这个问题，代码发现是获取不到屏幕的高度device.height和宽度device.width，写死就好了
系统版本 EMUI9.1

**Comment by Nick-Hopps** [comment]
还用着 EMUI8 的我，很多问题都不知道是怎么回事=。=

**Comment by YinHang119** [comment]
@DeserveL  麻烦问一下，是在哪个地方改呢 ？要写死成为自己手机屏幕的高度和宽度吗？谢谢！

**Comment by DeserveL** [comment]
@YinHang119 Unlock.js里面的80行  
   _HEIGHT = 手机分辨率高度,
    _WIDTH = 手机分辨率宽度,
先百度下自己手机的详细分辨率
