### ISSUE TITLE
蚂蚁森林更新后问题的部分解决方法

### ISSUE THREAD

**Issue by TonyJiangWJ** [Nick-Hopps/Ant-Forest-autoscript#68]
蚂蚁森林小程序里面把大部分脚本执行依赖的文字从desc移动到了text里面，我们把desc相关的方法都改成text，比如descContains改成textContains就行了，然后把获取好友列表的 idEndsWith("J_rank_list")改成 idEndsWith("J_rank_list_append")

**Comment by cyiande** [comment]
descEndsWith("背包").waitFor();
我现在卡在这里了，他找不到“背包”，请问有什么办法替代吗

**Comment by cyiande** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.view.accessibility.AccessibilityNodeInfo.getPackageName()'
descEndsWith("背包").waitFor();
我现在卡在这里了，他找不到“背包”，请问有什么办法替代吗

**Comment by TonyJiangWJ** [comment]
descEndsWith改成textEndsWith

**Comment by Nick-Hopps** [comment]
提个 pull 吧，我最近很忙没时间更新

**Comment by TonyJiangWJ** [comment]
我用的自己fork的脚本 魔改太多了，我晚上基于原版改一下再提交

**Comment by Nick-Hopps** [comment]
好的

**Comment by cyiande** [comment]
好了，已经可以运行了，谢谢，最开始只改了descContains，现在重新看才发现这是个例子，类似的都要改

**Comment by xapwv** [comment]
我收集好友能量时，排行榜快结束的时候，会停在那，!(textEndsWith("没有更多了").exists() && textEndsWith("没有更多了").findOne(_config.get("timeout_findOne")).bounds().centerY() < device.height)
，已经获取到这个控件，但其实屏幕上还没出现

**Comment by xapwv** [comment]
设置高度1920，得到的bounds().centerY() 1918，但是还没滑动出现"没有更多了"

**Comment by TonyJiangWJ** [comment]
没有出现“没有更多了” 我也遇到了 但是白天没时间测试，准备晚上看。
然后停在那里的话，
```javascript 
if (descEndsWith("关闭").exists()) descEndsWith("关闭").findOne(_config.get("timeout_findOne")).click(); 
```
保留为**descEndsWith** 不用修改为**textEndsWith**

**Comment by xapwv** [comment]
好像不是if (descEndsWith("关闭").exists()) descEndsWith("关闭").findOne(_config.get("timeout_findOne")).click(); 

是 if (descEndsWith("返回").exists()) descEndsWith("返回").findOne(_config.get("timeout_findOne")).click();

**Comment by TonyJiangWJ** [comment]
嗯 那我看错了，不过"关闭"这个也需要保留原来的 不要改成textEndsWith

**Comment by lunachy** [comment]
并不是所有的desc都无脑改成text，希望好好检查每个控件的详情

**Comment by TonyJiangWJ** [comment]
是今晚又更新了。。。

**Comment by TonyJiangWJ** [comment]
@Nick-Hopps 支付宝又改回去了，你要不直接回滚我的提交吧。我用我自己老的脚本代码运行没有问题，应该是又从text转回desc了。

**Comment by lunachy** [comment]
> @Nick-Hopps 支付宝又改回去了，你要不直接回滚我的提交吧。我用我自己老的脚本代码运行没有问题，应该是又从text转回desc了。

也不全是，首页的蚂蚁森林和好友排行榜这两个字段还是text，别的好像还是desc，可不可以用一种自适应的方式去解决这个经常改变的问题

**Comment by TonyJiangWJ** [comment]
> > @Nick-Hopps 支付宝又改回去了，你要不直接回滚我的提交吧。我用我自己老的脚本代码运行没有问题，应该是又从text转回desc了。
> 
> 也不全是，首页的蚂蚁森林和好友排行榜这两个字段还是text，别的好像还是desc，可不可以用一种自适应的方式去解决这个经常改变的问题

@abcd51685168 这两个本身就没有在上一个提交中修改，你先去看看提交记录，具体改了哪些都能看到的
