### ISSUE TITLE
pixel xl 手机解锁画面不上滑，无法弹出密码页面

### ISSUE THREAD

**Issue by xuchjian** [Nick-Hopps/Ant-Forest-autoscript#7]
pixel xl 手机解锁画面不上滑，无法弹出密码页面，无法进入系统

**Comment by Nick-Hopps** [comment]
这个是因为系统解锁屏幕控件 id 的问题，如果你会使用安卓 SDK 的 uiautomatorviewer 的话，就连上电脑看看解锁滑动屏幕的 id，然后替换 Unlock.js 中 device 的部分。
