### ISSUE TITLE
一加6运行最新版报错

### ISSUE THREAD

**Issue by woshixiaoxiaopeng** [Nick-Hopps/Ant-Forest-autoscript#72]
错误内容：TypeError：Cannot call method "forEach" of null (<update>#44)

**Comment by shinian97** [comment]
小米9运行后，进入蚂蚁森林直接不动了。

**Comment by YinHang119** [comment]
@guohuatai   我的三星S8也是这样，进去蚂蚁森林首页就停留在那，没反应

**Comment by wyfang** [comment]
小米9运行后，进入蚂蚁森林直接不动了。

**Comment by ore-lingyu** [comment]
荣耀10一样，点击main进入蚂蚁森林后没反应了，点击运行config报错（ReferenceError:activity is not defined ）

**Comment by YinHang119** [comment]
@guohuatai @ore-lingyu @wyfang   下载旧版本就好了，我下载的5月份以前的版本就可以正常运行
Ps更新的时候点取消
