### ISSUE TITLE
首次运行能打开蚂蚁森林，第二次就不行

### ISSUE THREAD

**Issue by xapwv** [Nick-Hopps/Ant-Forest-autoscript#76]
日志显示，直接收集自己能量，但是蚂蚁森林还没有打开。

**Comment by Nick-Hopps** [comment]
重启应用+重启无障碍服务，还是不行就检查是不是最新版本的 autojs

**Comment by ForgetSky** [comment]
> 重启应用+重启无障碍服务，还是不行就检查是不是最新版本的 autojs

重启还是不行，autojs是4.1.1

**Comment by Nick-Hopps** [comment]
> 
> 
> > 重启应用+重启无障碍服务，还是不行就检查是不是最新版本的 autojs
> 
> 重启还是不行，autojs是4.1.1

4.1.1 alpha 2 吗？

**Comment by xapwv** [comment]
我打印了日志，发现
` if (!textContains("蚂蚁森林").exists()) _start_app();`
是true，但是页面并没有打开

**Comment by ForgetSky** [comment]
> > > 重启应用+重启无障碍服务，还是不行就检查是不是最新版本的 autojs
> > 
> > 
> > 重启还是不行，autojs是4.1.1
> 
> 4.1.1 alpha 2 吗？

是的

**Comment by Godsing** [comment]
我在小米8上也是同样的问题，试着在 `_start_app ` 函数定义的最后加上一句 `sleep(2000);`，就成功了，你试试~

**Comment by Godsing** [comment]
> > 4.1.1 alpha 2 吗？
> 
> 是的

对了，顺便咨询一下，我这里运行到最后 `floaty.window()` 这函数会报错，我猜可能是 AutoJS 版本不够新的问题。我现在用的是 4.0.1 Beta 版本。
想去 GitHub 官方repo的 [releases](https://github.com/hyb1996/Auto.js/releases) 找，最新的也只有 4.0.5Alpha ，请问哪里有 4.1.1 alpha 2 可以下载？

**Comment by Nick-Hopps** [comment]
> 
> 
> > > 4.1.1 alpha 2 吗？
> > 
> > 
> > 是的
> 
> 对了，顺便咨询一下，我这里运行到最后 `floaty.window()` 这函数会报错，我猜可能是 AutoJS 版本不够新的问题。我现在用的是 4.0.1 Beta 版本。
> 想去 GitHub 官方repo的 [releases](https://github.com/hyb1996/Auto.js/releases) 找，最新的也只有 4.0.5Alpha ，请问哪里有 4.1.1 alpha 2 可以下载？

贴吧，只看楼主

**Comment by ForgetSky** [comment]
> 我在小米8上也是同样的问题，试着在 `_start_app ` 函数定义的最后加上一句 `sleep(2000);`，就成功了，你试试~

没有用

**Comment by xapwv** [comment]
> > 我在小米8上也是同样的问题，试着在 `_start_app ` 函数定义的最后加上一句 `sleep(2000);`，就成功了，你试试~
> 
> 没有用

`while(!descContains("蚂蚁森林").exists()) { _start_app(); }`
试试循环吧

**Comment by ForgetSky** [comment]
> > > 我在小米8上也是同样的问题，试着在 `_start_app ` 函数定义的最后加上一句 `sleep(2000);`，就成功了，你试试~
> > 
> > 
> > 没有用
> 
> `while(!descContains("蚂蚁森林").exists()) { _start_app(); }`
> 试试循环吧

延时足够，循环多次也还是打不开

**Comment by TonyJiangWJ** [comment]
MIUI打不开的，后台长按AutoJs，然后进到权限管理，把AutoJs的权限放开 修改系统设置等等

**Comment by TonyJiangWJ** [comment]
> MIUI打不开的，后台长按AutoJs，然后进到权限管理，把AutoJs的权限放开 修改系统设置等等

还有后台弹出界面，我是全部都勾选了 没去试到底哪一项权限

**Comment by xapwv** [comment]
蚂蚁森林是不是有更新了，今天下午又停留在自己页面

**Comment by Nick-Hopps** [comment]
> 
> 
> 蚂蚁森林是不是有更新了，今天下午又停留在自己页面

没有，应该是公益林那个东西

**Comment by xapwv** [comment]
> > 蚂蚁森林是不是有更新了，今天下午又停留在自己页面
> 
> 没有，应该是公益林那个东西

大哥，有解决方案么

**Comment by lyings** [comment]
最新的蚂蚁森林这个项目已经不能用了运行后卡在我蚂蚁森林首页，(ps:  4.1.1 alpha 2 有个bug 。项目中只要调用了home()方法，就再也打不开app应用了，我用了另一个项目的方法重写了退出应用的函数，来避免使用home()函数) 。

**Comment by lyings** [comment]
解决了吗？就关闭了

**Comment by ForgetSky** [comment]
不是home()的原因，不用也不行

**Comment by xapwv** [comment]
还没有解决，头疼
