### ISSUE TITLE
运行config.py会提示activity is not defined

### ISSUE THREAD

**Issue by mx935121796** [Nick-Hopps/Ant-Forest-autoscript#77]

**Comment by ysinsane** [comment]
我也是，调试了好久。

**Comment by Nick-Hopps** [comment]
你想说的是 config.js 吧？这个问题一般都是因为软件太旧导致的，记得是 autojs 4.1.1 alpha 2

**Comment by Nick-Hopps** [comment]
贴吧里面有上传

**Comment by mx935121796** [comment]
大写的谢谢。


 
---原始邮件---
发件人: "Nick_Hopps"<notifications@github.com>
发送时间: 2019年6月9日(星期日) 凌晨3:05
收件人: "Nick-Hopps/Ant-Forest-autoscript"<Ant-Forest-autoscript@noreply.github.com>;
抄送: "mx935121796"<935121796@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Nick-Hopps/Ant-Forest-autoscript] 运行config.py会提示activity is not defined (#77)



贴吧里面有上传

**Comment by TonyJiangWJ** [comment]
贴吧里面的好像被度娘吃了。。。
[AutoJs 4.1.1 alpha2下载](https://www.dropbox.com/s/pe3w53k0fugo1fa/Autojs%204.1.1%20Alpha2.apk?dl=0)

**Comment by Nick-Hopps** [comment]
现在可以进QQ群下载了
