### ISSUE TITLE
荣耀畅玩6x不能解锁

### ISSUE THREAD

**Issue by lowbibi** [Nick-Hopps/Ant-Forest-autoscript#8]
大佬，脚本可以收取能量。如果锁频的话，亮屏后不能滑动进入解锁界面，也就无法输入密码解锁了，望大佬修复。感谢

**Comment by Nick-Hopps** [comment]
奇怪。。。华为的不应该都一样吗(๑˙ー˙๑)

**Comment by Nick-Hopps** [comment]
参考一下 issue #7

**Comment by lowbibi** [comment]
大佬，不会用啊。怎么办？需要连接电脑查看吗？

**Comment by Nick-Hopps** [comment]
很简单的，百度/Google一下安卓 uiautomatorviewer 找找教程，是要连电脑的
