### ISSUE TITLE
荣耀V20，系统安卓9，屏幕2310×1080；Auto.js_4.0.5 Alpha 脚本是刚刚下载使用的

### ISSUE THREAD

**Issue by XmJwit** [Nick-Hopps/Ant-Forest-autoscript#82]
报错日志：
![Screenshot_20190612_232041](https://user-images.githubusercontent.com/36185379/59364406-6198d800-8d69-11e9-8853-0ed1933b9052.jpg)
![Screenshot_20190612_232110](https://user-images.githubusercontent.com/36185379/59364431-6a89a980-8d69-11e9-836f-69e245435a17.jpg)
![Screenshot_20190612_232122](https://user-images.githubusercontent.com/36185379/59364443-6e1d3080-8d69-11e9-9083-8cb8b8fd14cc.jpg)
原谅我不能复制，因为复制不了QAQ
具体bug就是：config.js运行失败，main.js可以打开对应的支付宝里的蚂蚁森林，而后在打开好友森林bug了

**Comment by Nick-Hopps** [comment]
软件版本的问题，加QQ群，里面有最新的软件
