### ISSUE TITLE
config运行失败，脚本没考虑支付宝指纹到密码的切换

### ISSUE THREAD

**Issue by zb861359** [Nick-Hopps/Ant-Forest-autoscript#85]
1. 运行config.js时，报错，错误: ReferenceError :" activity " is not defined .(--ui--. js #15)
2. 未考虑支付宝开启方式，现在都用指纹，脚本中需切换到密码模式，输入密码xxxxx
3. 运行update.js下载失败

**Comment by Nick-Hopps** [comment]
1. 软件版本太旧
2. 亮屏滑动解锁跟指纹解锁没有关系
3. 软件版本太旧

**Comment by zb861359** [comment]
软件版本太旧，指的是autojs太旧？
指纹切换到密码，是指进入支付宝，不是手机解锁。现在支付宝不都是用指纹保护的吗

**Comment by Nick-Hopps** [comment]
这个没办法的，想用就关掉指纹解锁，反正我一直都没有设置应用锁

**Comment by zb861359** [comment]
我对js脚本不熟，请教下，我们这里打开支付宝的地方在哪里，只找到了打开蚂蚁森林，如下
// 进入蚂蚁森林主页
  const _start_app = function() {
    app.startActivity({????????
      action: "VIEW",
      data: "alipays://platformapi/startapp?appId=60000002",????
    });
  }
我已经实现了从指纹切换到输入密码，开启支付宝。

**Comment by Nick-Hopps** [comment]
不是这个的问题，而是脚本并没有考虑你进支付宝还要输入密码，因此如果你实在不想去掉密码，你只能自己写一个输入密码的脚本了

**Comment by zb861359** [comment]
我已经实现了输入密码的脚本，现在只需要找到我们项目里打开支付宝的地方就可以了，我用launchAPP（“支付宝”）打开的

**Comment by Nick-Hopps** [comment]
好的，那就没问题，你就把解锁代码丢到 _start_app 这个函数里面就好，然后调整一下延时

**Comment by zb861359** [comment]
直接放到函数体的最上边？那不就多开了一次支付宝吗

**Comment by Nick-Hopps** [comment]
你放到下面试一下

**Comment by zb861359** [comment]
好的，我试试。
还有其他问题，update那个老出错，我直接在main中屏蔽它后，打不开支付宝了

**Comment by Nick-Hopps** [comment]
update出错？你用的什么版本的autojs？

**Comment by zb861359** [comment]
4.0.0beta版

**Comment by Nick-Hopps** [comment]
看我第一个回答

**Comment by Nick-Hopps** [comment]
加群下载 autojs 4.1.1 Alpha 2 版本

**Comment by zb861359** [comment]
大神，下了4.1.1，config可以用了，但update仍然提示下载失败

**Comment by zb861359** [comment]
具体提示如下，这个文件明明存在啊
14:38:44.563/E: 下载失败：JavaException: java.io.FileNotFoundException: 内部存储/脚本/Ant-Forest-autoscript/CHANGELOG.md (No such file or directory)
