### ISSUE TITLE
华为荣耀v10报错

### ISSUE THREAD

**Issue by icedifferent** [Nick-Hopps/Ant-Forest-autoscript#9]
新版本报错，旧版本好像没啥问题（如有再补充）
autojs  4.0.5Alpha 版本

![_20190208141941](https://user-images.githubusercontent.com/20622753/52462226-244eee80-2bad-11e9-8d2a-da99f6873b8b.png)

**Comment by Nick-Hopps** [comment]
这个是软件的问题了，不可抗力的BUG

**Comment by Nick-Hopps** [comment]
目前我使用的版本是 4.1.0，你也可以试试重启 autojs 再看看，有时候软件读取不到控件ID也会这样。
