### ISSUE TITLE
最近是不是有更新了!?

### ISSUE THREAD

**Issue by wyfang** [Nick-Hopps/Ant-Forest-autoscript#92]
手上两台手机：小米9、坚果pro2s

每次更新玩，都是轮流两个手机一个能用一个不能用。

更新前是小米9进入森林后就没动作了；坚果可以正常使用。

更新后，坚果不行了，小米9又恢复正常了，这和上次更新一样。

**Comment by wyfang** [comment]
怎么突然今天又可以了呢？没看到更新啊。

**Comment by Nick-Hopps** [comment]
emmm，软件蜜汁问题？

**Comment by wyfang** [comment]
> emmm，软件蜜汁问题？

是啊，不过我认真回想了下，似乎和森林的限时活动有关系
