### ISSUE TITLE
点击main启动，直到下拉完排行榜之后报了一个错误

### ISSUE THREAD

**Issue by nanjunyu** [Nick-Hopps/Ant-Forest-autoscript#95]
作者你好，感谢分享，
请我点击main启动，直到下拉完排行榜之后报了一个错误，请问这个怎么排查，手机是小米8
系统版本miui10.9.6.27 开发版  auto.js版本 4.0.1  支付宝版本10.1.68
![image](https://user-images.githubusercontent.com/23097168/60705363-897af600-9f39-11e9-9534-e1048d2d3d76.png)

**Comment by nanjunyu** [comment]
![image](https://user-images.githubusercontent.com/23097168/60705944-f347cf80-9f3a-11e9-9712-c081cb810137.png)
另外运行config.js直接报错

**Comment by Nick-Hopps** [comment]
autojs 的版本太旧了，加群下载新版本吧
